name: docker_register_cloud
description: The network disk client based on the Docker warehouse protocol can use many free container warehouse services for network disk storage, download and sharing.
version: 2.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  args: ^2.0.0
  http: ^0.12.1
  chewie: ^1.2.2
  crypto: ^2.1.3
  filesize: ^2.0.1
  provider: ^5.0.0
  open_file: ^3.0.1
  url_launcher: ^6.0.5
  angel_static: ^2.1.3
  synchronized: ^3.0.0
  video_player_web: ^2.0.4
  filesystem_picker:
    git:
      url: https://github.com/kuchienkz/filesystem_picker.git
      path: package
  path_provider: ^1.6.8
  angel_framework: ^2.0.0
  json_annotation: ^4.0.0
  shared_preferences: ^0.5.7
  permission_handler: ^5.0.0
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^4.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: DroidSansFallback
      fonts:
        - asset: fonts/DroidSansFallback.ttf
